- name: Semaphore
  hosts: all
  become: true
  vars_files:
    - "env_vars/semaphore.yml"
  tasks:

    - name: Create required users
      ansible.builtin.user:
        name: "{{ semaphore_user }}"
  
    - name: Create directory for config
      ansible.builtin.file:
        path: "/opt/ansible"
        state: directory
        mode: '0755'
        owner:  "{{ semaphore_user }}"
        group:  "{{ semaphore_user }}"
        recurse: true

    - name: Install semaphore deb
      ansible.builtin.apt:
        deb: "https://github.com/ansible-semaphore/semaphore/releases/download/v{{ semaphore_version }}/semaphore_{{ semaphore_version }}_linux_amd64.deb"

    - name: Create config
      ansible.builtin.template:
        src: "templates/config.json.j2"
        dest: "{{ semaphore_home }}/{{ semaphore_config_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Get admin user
      ansible.builtin.command:
        cmd: semaphore user get --login={{ semaphore_admin_user }} --config={{ semaphore_home }}/{{ semaphore_config_file }}
      register: result
      failed_when: false
      changed_when: false

    - name: Create admin user
      ansible.builtin.command:
        cmd: semaphore user add --admin --login={{ semaphore_admin_user }} --password={{ semaphore_admin_password }} --name {{ semaphore_admin_user }} --email={{ semaphore_admin_email }} --config={{ semaphore_home }}/{{ semaphore_config_file }}
      # when: result is failed

    - name: Create systemd file
      ansible.builtin.template:
        src: "templates/semaphore.service.j2"
        dest: "/etc/systemd/system/semaphore.service"
        owner: root
        group: root
        mode: '0644'

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start semaphore
      ansible.builtin.systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: semaphore
