- name: Deploy application
  hosts: all
  become: yes
  vars:
    app_user: ryan_user
    app_dir: /opt/myapp
    virtualenv_dir: /opt/myapp/venv
    repo_url: https://gist.github.com/thibaultserti/21456f4797100376f67443920e5d5145/archive/main.zip

  tasks:
    - name: Install Python et Unzip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-venv
        - unzip

    - name: Download Github Code
      get_url:
        url: "{{ repo_url }}"
        dest: /tmp/myapp.zip

    - name: Creation User
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        create_home: yes
