- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - git
          - apache2
          - python3-pip
        state: present

    - name: Clone repository
      git:
        repo: 'https:/github.com/xNer0/semui.co.git'
        dest: /var/www/semui.co

    - name: Install Python requirements
      pip:
        requirements: /var/www/semui.co/requirements.txt

    - name: Configure Apache
      copy:
        src: apache_config
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644

    - name: Enable site
      command: a2ensite 000-default

    - name: Disable default site
      command: a2dissite 000-default

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
